# SIZES
CELL_SIZE = 16
SCALE = 2

WIDTH = CELL_SIZE * SCALE * 30
HEIGHT = CELL_SIZE * SCALE * 20
RESOLUTION = (WIDTH, HEIGHT)

HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
ABSOLUTE_CENTER = (HALF_WIDTH, HALF_HEIGHT)

# FILES
IMAGE_PATH = 'images'
SOUND_PATH = 'sounds'

# IN_GAME PARAMETERS
SCREEN_DEPTH = 1
SCREEN_FLAGS = 0
FPS = 90
ANIMATION_CHANGE = 60

# COLORS
BLACK = 'black'
